services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quarkus_vector_postgres
    user: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vctordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-data:/docker-entrypoint-initdb.d/
volumes:
  postgres_data: